### ISSUE TITLE
Toggle Between Vertical and Horizontal Direction

### ISSUE THREAD

**Issue by hellotherekevin** [PEZ/SketchDistributor#13]
It would be great to be able to toggle between the Vertical and Horizontal directions with a keyboard shortcut.

I love this plugin and use it every day! Thanks!

**Comment by PEZ** [comment]
Thanks! I have just updated the plugin with two keyboard shortcuts so that if you invoke Distributor with <kbd>CTRL</kbd>+<kbd>OPTION</kbd>+<kbd>V</kbd> and <kbd>CTRL</kbd>+<kbd>OPTION</kbd>+<kbd>H</kbd>, you will get vertical or horizontal distribution, respectively, selected in the dialog. And then you can just enter the spacing and hit <kbd>ENTER</kbd>.

I hope this will improve your workflow.

**Comment by hellotherekevin** [comment]
This is awesome! Thanks for doing this so quickly 👍
