### ISSUE TITLE
[Bug] Plugin Doesn't Work in Sketch Version 72

### ISSUE THREAD

**Issue by leon-applab** [PEZ/SketchDistributor#32]
The distributor plugin stop working in Sketch Version 72. After entered the spacing value and hit "OK", nothing happen.

**Comment by Jakamal781** [comment]
Having the same problem as leon-applab. The plugin stopped working once I upgraded to Sketch V.72

**Comment by PEZ** [comment]
I'm sorry about this. I don't have a Sketch license so I can't really fix the issue.

**Comment by rmirre** [comment]
@PEZ Could we all donate a bit to help you get back up with a license? I know I would be happy to chip in.

**Comment by drumphil42** [comment]
Very sad to see this not working anymore.  I relied on it a lot because the native Sketch distribute is so bad. I would definitely donate to help fix this.

**Comment by PEZ** [comment]
Hello, I started a trial of Sketch with a throwaway e-mail address so could reproduce the error. Distributor relies on non-public API:s (as do many Sketch plugins, since the public API:s used to be super limited), and now and then these API:s (if you can even call it that) change. This was such an event.

I think I have fixed it now. At least the obvious cases work for me in Sketch 72.2 Beta. Can some you upgrade to 1.2.3 and put it through some tests?

@rmirre and @drumphil42 , I totally appreciate your offer to chip in for a licence! Two reasons why I hesitated about that:

1. It would make me feel obliged to fix it. And since the API:s can change pretty wildly, I am never sure I can fix problems like this within some reasonable amount of time.
2. I think that Bohemian should provide the author of this kind of plugin (proven, quite popular, letting them focus on other things, etcetera) with a developer's licence). (They actually used to extend my code for some months on my requests, but then stopped doing that. I think it was a bother to have to ask them and then wait for it to happen and such, but it was better than nothing.)

Anyway, maybe it is time we try to find a developer who is actually using Sketch to adopt this plugin.

**Comment by PEZ** [comment]
I now advertised Distributor is up for adoption by some kind dev:

https://sketchplugins.com/d/2362-please-adopt-sketch-distributor

Please consider joining the discussion over there and chime in.

**Comment by leon-applab** [comment]
> Hello, I started a trial of Sketch with a throwaway e-mail address so could reproduce the error. Distributor relies on non-public API:s (as do many Sketch plugins, since the public API:s used to be super limited), and now and then these API:s (if you can even call it that) change. This was such an event.
> 
> I think I have fixed it now. At least the obvious cases work for me in Sketch 72.2 Beta. Can some you upgrade to 1.2.3 and put it through some tests?
> 
> @rmirre and @drumphil42 , I totally appreciate your offer to chip in for a licence! Two reasons why I hesitated about that:
> 
> 1. It would make me feel obliged to fix it. And since the API:s can change pretty wildly, I am never sure I can fix problems like this within some reasonable amount of time.
> 2. I think that Bohemian should provide the author of this kind of plugin (proven, quite popular, letting them focus on other things, etcetera) with a developer's licence). (They actually used to extend my code for some months on my requests, but then stopped doing that. I think it was a bother to have to ask them and then wait for it to happen and such, but it was better than nothing.)
> 
> Anyway, maybe it is time we try to find a developer who is actually using Sketch to adopt this plugin.

Hi @PEZ , thank you very much for taking time to help us fix the issue. The plugin works perfectly fine now in Sketch 72. 

Although it might be just a small and simple plugin, it definitely take an important role in my daily mobile app design workflow. It has saved me a lot time from moving my mouse cursor to the side inspector to distribute layers / groups / artboards. With this plugin, I can use the shortcuts to call the distribute functions easier and faster. It maybe just 1 or 2 seconds faster compare to using the Sketch default side inspector distribute function, but when this action repeat tons of times daily, the amount of time it saved is significant. 

It's sad to hear that you might not continue maintaining this plugin, I still appreciate your time and hard work for created this small plugin that make huge enhancement to my workflow. 👍

**Comment by rmirre** [comment]
Thank you @PEZ 

I totally understand that hesitation and would say even if you are looking for someone to adopt it, you might want to consider one of those 'buy me a coffee' type of donation things. I know I would be very happy to just send a small token of thanks for making my daily work life easier, and I am sure others would too. And I totally echo the thoughts of @leon-applab, well stated.
