### ISSUE TITLE
Cache direction selection (horizontal/vertical radio buttons)

### ISSUE THREAD

**Issue by arturmuller** [PEZ/SketchDistributor#4]
It would be awesome if you would cache these the same way you do it with the distance values. It's a huge time-saver, especially if you do multiple identical operations one after another.

(BTW this plugin is really amazing — I use it almost every day and it is my far my most used plugin in Sketch. Thanks!)

**Comment by PEZ** [comment]
Thanks for that kind feedback! Of course the plugin should remember the direction between runs too. Now fixed!

**Comment by arturmuller** [comment]
Thanks! Amazing! :+1:

**Comment by PEZ** [comment]
I just added so that you can repeat a distribution using the last settings for direction and spacing without bringing up the dialog. To not clutter peoples plugin menus too much the two ways to invoke distribution are now submenus to _Distributor_. While that puts it one more click away I have also added keyboard shortcuts. `Shift + Control + D` for bringing the dialog up, and `Shift + Control + A` for _Distribute again_. I hope it can save you some clicking. =)

**Comment by arturmuller** [comment]
Excellent! Thanks again! :)

**Comment by PEZ** [comment]
The current version tries to improve the workflow some more by adding keyboard shortcuts for horizontal and vertical distribution, respectively. It also autofocuses on the spacing field. FYI. 😀
