### ISSUE TITLE
Sketch 3.4.2 compatibilty?

### ISSUE THREAD

**Issue by ghost** [PEZ/SketchDistributor#5]
Does this plugin work with newest Sketch?

No matter how many object I select in the dialog it always says "Distribute 1 objects".

**Comment by PEZ** [comment]
I'm sorry about those problems. I think you are running into a bug in Sketch 3.4.2 which makes it confuse which document the plugin is invoked on. Can you try restarting Sketch and only have one document active and see if that helps? If so, it strengthens the suspicion on the 3.4.2 bug. If not, then there might be a problem with the plugin. I will try to reproduce the problem and see what I can do, regardless if this is caused by Sketch or by me.

**Comment by ghost** [comment]
You are right, it seems that you can't have more then one sketch file open
:D

Good work on the plugin btw!

Maybe a cool feature would be a distribute function in which you input the
total width, not the spacing between elements.
I know sketch has it integrated but it doesn't work really good.

Regards,

Ivan

On Tue, Nov 24, 2015 at 1:25 PM, Peter Strömberg notifications@github.com
wrote:

> I'm sorry about those problems. I think you are running into a bug in
> Sketch 3.4.2 which makes it confuse which document the plugin is invoked
> on. Can you try restarting Sketch and only have one document active and see
> if that helps? If so, it strengthens the suspicion on the 3.4.2 bug. If
> not, then there might be a problem with the plugin. I will try to reproduce
> the problem and see what I can do, regardless if this is caused by Sketch
> or by me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PEZ/SketchDistributor/issues/5#issuecomment-159252317
> .

##

**Comment by PEZ** [comment]
Thanks for quick response! I will try find a way to work around the bug.

For my book keeping it would be nice to have your feature request as a separate issue. =)

**Comment by PEZ** [comment]
@SkoroIvan : I have now updated the plugin with a workaround so that it should behave even when you have several documents open. I am fairly certain the workaround does the trick, but as I fail to reproduce your issue on my machine I am not sure. I would very much appreciate if you could update the plugin and try it for me.

**Comment by ghost** [comment]
Fuck yeah man it works. I wish all sketch plugins developers were like
this.
Thanks!

On Wed, Nov 25, 2015 at 10:35 AM, Peter Strömberg notifications@github.com
wrote:

> @SkoroIvan https://github.com/SkoroIvan : I have now updated the plugin
> with a workaround so that it should behave even when you have several
> documents open. I am fairly certain the workaround does the trick, but as I
> fail to reproduce your issue on my machine I am not sure. I would very much
> appreciate if you could update the plugin and try it for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PEZ/SketchDistributor/issues/5#issuecomment-159549647
> .

##

**Comment by PEZ** [comment]
Awwww! Thanks!
